### ISSUE TITLE
Rename volume vgroup column in views to group

### ISSUE THREAD

**Issue by icot** [cerndb/dbod-api#30]
While the name is actually _maybe_ clearer for the DB schema, if we expose the vgroup name the result can't not be used directly later on without mapping it to the right value

**Comment by Joscorbe** [comment]
group is a reserved word in sql, that's the reason we used the vgroup name.

**Comment by Joscorbe** [comment]
We could escape the name using double quotes ("group"), but this could introduce some problems:
1- We don't know how PostgREST and other systems work, and maybe they don't use always the quotes.
2- PostgREST folds all identifiers to lowercase, but if they are escaped the fold is not done. That means "group" won't be the same as "Group" or "GROUP" (which could give the same issues of the first point).
