### ISSUE TITLE
Move common functions from public to api schema

### ISSUE THREAD

**Issue by Joscorbe** [cerndb/dbod-api#70]
For 0.8 milestone I will need to move (or duplicate) the "get_attributes" function from public to api schema to be usable from PostgREST.
I wonder if would have sense to move also all the functions, to avoid having some in public and others in api.

**Comment by icot** [comment]
A couple of comments: 
- Never duplicate code, that would be a mess to maintain further on.
- It's a matter of how do want to see the encapsulation. If you consider these procedures as accessors to the main schema tables and data, they should be kept there. Let's say that the attribute table changes in a way that the `get_attributes` needs to be modified to maintain API compatibility. You should then modify code (SQL definitions) in two different places
