### ISSUE TITLE
Implement list instances endpoint

### ISSUE THREAD

**Issue by Joscorbe** [cerndb/dbod-api#92]
Endpoint to list all instances by user
Endpoint to list all instances by egroup
Endpoint to list all instances (for admins)

**Comment by icot** [comment]
As discussed, we will implement this as a single endpoint to which we will supplyan object describing the resources owned by the user. This object will be generated during authentication.
Examle:
```json
{
"instances": ["a", "b"],
"clusters": ["Ca", "Cb"],
"egroups": ["group_a", "group_b"]
}
```

**Comment by icot** [comment]
Done
