### ISSUE TITLE
Correction and improvement of logging

### ISSUE THREAD

**Issue by Joscorbe** [cerndb/dbod-api#93]
Logs have to be improved in some endpoints.

**Comment by icot** [comment]
Can you ellaborate with concrete examples?

**Comment by Joscorbe** [comment]
To be discussed. Probably this issue has no sense now as the logic of the endpoints has changed considerably with the last changes.

For example, the logging of the PUT instance endpoint was mostly useless, as the format of the output was different as for another endpoints. This issue had as objective to standarize the way we output the loggin for all the endpoints.
